name: habitreminder
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.4
  uuid: ^4.5.0
  timezone: ^0.9.4
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Black.ttf
          weight: 900
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 600
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300

